[package]
name = "fitness_coder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
requestty = "0.4.1"
serde_json = "1.0.87"
