[package]
name = "fitness_coder"
version = "0.1.1"
edition = "2021"
description = "A fitness freak's toy."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
requestty = "0.4.1"
